변수란 하나의 값을 갖고 있는 것,

변수 여러개의 값을 할당한다 -> 리스트, 튜플, 딕셔너리

변수에 숫자 데이터가 많은 경우에는 리스트의 속도가 느려지고,
메모리를 많이 차지하는 단점이 발생한다.

이러한 단점을 보완하기 위하여 배열(array)을 사용하면, 적은 메모리로 대용량의 데이터를 처리할 수 있다.

### 배열이 리스트와 다른 점

- 배열의 모든 원소가 같은 자료형이어야 한다.
- 원소의 개수를 바꿀 수 없다.

배열을 사용하기 위하여 넘파이 모듈을 호출한다.

In [1]:
import numpy as np

# 1차원 배열 만들기

In [3]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
type(arr)

numpy.ndarray

## 리스트 대신 배열을 사용해야 하는 이유

In [8]:
data = [0,1,2,3,4,5,6,7,8,9]
data2 = []

In [9]:
for i in data:
    data2.append(i*2)
data2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

## 배열을 사용하면 for문 사용없이 연산이 가능함

In [10]:
arr2 = arr*2
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])

2 * a + b

array([ 6,  9, 12])

# 2차원 배열 : 행렬 Matrix 매트릭스
- 1차원배열 = 행 또는 열로만 구성
- 2차원배열 = (행,열)로 구성


In [15]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
d = np.array([[10,20,30,40],
            [50,60,70,80]])
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

# 3차원 배열 : [[[3차원배열]]]

In [25]:
e = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
             [[1,2,3,4],[5,6,7,8],[9,10,11,12]]]) # 2*3*4 배열 
e

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

# 배열이 몇차원인지, 크기 알아내기

In [33]:
a = np.array([1,2,3])
a.ndim # 차원

1

In [34]:
a.shape # 크기

(3,)

In [35]:
e = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
             [[1,2,3,4],[5,6,7,8],[9,10,11,12]]]) # 2*3*4 배열 
e

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [36]:
e.ndim

3

In [37]:
e.shape # 2행 3열 4면

(2, 3, 4)

In [38]:
d = np.array([[10,20,30,40],
            [50,60,70,80]])
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [40]:
d.ndim

2

In [41]:
d.shape

(2, 4)

# 배열의 인덱싱

In [42]:
a = np.array([0,1,2,3,4])

In [43]:
a[2]

2

In [44]:
a[-1]

4

In [45]:
a[:]

array([0, 1, 2, 3, 4])

In [47]:
a[::-1]

array([4, 3, 2, 1, 0])

# 2차원 배열

In [54]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [55]:
b.ndim

2

**다차원 배열일 경우**
- 콤마 기호를 사용하여 접근할 수 있다.

In [56]:
b[0,1] # 1번째 행에서 2번째 열의 값을 가져옴

2

In [60]:
b[2,2]
b[1,1]

5